
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PERIOD = 34;
  public static final int LPAREN = 26;
  public static final int PRINTLN = 10;
  public static final int MINUS = 23;
  public static final int DOUBLETYPE = 13;
  public static final int RPAREN = 27;
  public static final int LFREEBRACE = 30;
  public static final int SEMICOLON = 32;
  public static final int AND = 21;
  public static final int LT = 22;
  public static final int BANG = 25;
  public static final int COMMA = 33;
  public static final int CLASS = 4;
  public static final int PLUS = 19;
  public static final int MAIN = 3;
  public static final int IF = 7;
  public static final int THIS = 16;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int DOUBLELITERAL = 37;
  public static final int TRUE = 17;
  public static final int RFREEBRACE = 31;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int INTEGERLITERAL = 36;
  public static final int BOOLEANTYPE = 6;
  public static final int BECOMES = 20;
  public static final int TIMES = 24;
  public static final int LBRACE = 28;
  public static final int ELSE = 8;
  public static final int WHILE = 9;
  public static final int PUBLIC = 2;
  public static final int INTTYPE = 12;
  public static final int RBRACE = 29;
  public static final int EXTENDS = 5;
  public static final int FALSE = 18;
  public static final int LENGTH = 11;
  public static final int IDENTIFIER = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "MAIN",
  "CLASS",
  "EXTENDS",
  "BOOLEANTYPE",
  "IF",
  "ELSE",
  "WHILE",
  "PRINTLN",
  "LENGTH",
  "INTTYPE",
  "DOUBLETYPE",
  "NEW",
  "RETURN",
  "THIS",
  "TRUE",
  "FALSE",
  "PLUS",
  "BECOMES",
  "AND",
  "LT",
  "MINUS",
  "TIMES",
  "BANG",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LFREEBRACE",
  "RFREEBRACE",
  "SEMICOLON",
  "COMMA",
  "PERIOD",
  "IDENTIFIER",
  "INTEGERLITERAL",
  "DOUBLELITERAL"
  };
}

